"""Bind a sampled MedGemma report to this study's actual rendered input images.

Reports provide axial planes, not lesion coordinates. Never synthesize point findings.
"""
import base64
import hashlib
import io
import json
from pathlib import Path

import numpy as np

from .slice_input import SliceInputs


def load_review(study, report_path=None):
    explicit = report_path is not None
    if not explicit:
        candidates = sorted(Path(study.analysis).glob('medgemma-review-*.json'),
                            key=lambda path: path.stat().st_mtime_ns, reverse=True)
        if not candidates:
            return {"status": "absent", "message": "No local MedGemma report embedded. Run medgemma review, or build with --medgemma-report PATH."}
        report_path = candidates[0]
    path = Path(report_path).expanduser()
    try:
        report = json.loads(path.read_text())
        if not report.get('workflow', '').startswith('aligned-slices-'):
            raise ValueError('Only aligned-slice reports have navigable review planes')
        if report.get('status') != 'complete':
            raise ValueError('Report is incomplete; no review planes were embedded')
        inputs = SliceInputs(study)
        plan = report['sampling']
        if (plan['shape'] != list(inputs.ref.shape) or plan['reference'] != inputs.reference
                or not np.allclose(plan['spacing_mm'], inputs.spacing, atol=1e-5)):
            raise ValueError('Report geometry does not match this study')
        sequences = report['sequences']
        if not sequences or len(set(sequences)) != len(sequences) or any(s not in inputs.available for s in sequences):
            raise ValueError('Report sequences do not match this study')
        rows = report['reviews']
        if not rows or len(rows) != report['planned_slices']:
            raise ValueError('Report slice count is incomplete')
        result = []
        for row in rows:
            if row['decision']['review'] not in ('yes', 'no', 'uncertain', 'invalid'):
                raise ValueError('Unknown report decision')
            _, images = inputs.render(row['z'], sequences)
            saved = row['images']
            if len(images) != len(saved):
                raise ValueError('Report image count does not match sequence count')
            frames = []
            for sequence, image, record in zip(sequences, images, saved):
                stream = io.BytesIO()
                image.save(stream, format='PNG')
                blob = stream.getvalue()
                if record['sequence'] != sequence or hashlib.sha256(blob).hexdigest() != record['sha256']:
                    raise ValueError('Report inputs differ from the current study; rerun review after image/role changes')
                # Embed verified regenerated bytes, never arbitrary report paths/URLs.
                frames.append({'sequence': sequence, 'src': 'data:image/png;base64,' + base64.b64encode(blob).decode()})
            result.append({'z': row['z'], 'decision': row['decision'], 'text': row['text'],
                           'prompt': row['prompt'], 'images': frames})
        return {'status': 'complete', 'source': path.name, 'model': report.get('model_provenance', {}),
                'development_limit': report.get('development_limit'), 'sampling_mm': plan['step_mm_actual'],
                'sequences': sequences, 'reviews': result}
    except (ValueError, KeyError, TypeError, OSError, AttributeError, IndexError) as exc:
        if explicit:
            raise ValueError(f'Cannot attach MedGemma report: {exc}') from exc
        return {'status': 'unavailable', 'message': f'Latest report not attached: {exc}'}
